services:
  - type: web
    name: discord-bot-so
    env: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
